function [ EVENT_CODES, EVENT_NAMES ] = event_codes()
EVENT_CODES = struct(...
    'Calibration_Start', 1, ...
    'Calibration_End', 2, ...
    'Attract_Attention_Start', 3, ...
    'Attract_Attention_End', 4, ...
    'Manual_Juice_Start', 5, ...
    'Manual_Juice_End', 6, ...
    'Drift_Correct', 7, ...
    ...
    'Trial_Start', 8, ...
    'Fixation_Shown', 9, ...
    'Fixated', 10, ...
    'Sample_Start', 11, ...
    'Delay_Start', 12, ...
    'Test_Start', 13, ...
    'Saccade_Start', 14, ...
    ...
    'Initial_Fixation_Lost', 16, ...
    'Fixation_Lost', 17, ...
    'Missed_Target', 18, ...
    'Correct', 19, ...
    'Incorrect', 20, ...
    ...
    'Dot_Condition', 25, ....
    'Color_Condition', 26, ....
    ...
    'Paradigm_Start', 30, ...
    'Paradigm_End', 31 ...
);

for i = 32:255
	EVENT_CODES.(['Condition_' num2str(i-31)]) = i;
end

EVENT_NAMES = cell(1, 255);
names = fieldnames(EVENT_CODES);
for i = 1:length(names)
    name = names{i};
    code = EVENT_CODES.(name);
    if ~isempty(EVENT_NAMES{code})
        error('duplicate names for event code');
    end
    EVENT_NAMES{code} = name;
end
end

